DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USERNAME        VARCHAR(32) PRIMARY KEY,
    BIRTH_DATE      VARCHAR(10) NOT NULL,
    USER_IDENTITY   VARCHAR(5) NOT NULL,
    PWD             VARCHAR(255) NOT NULL,
    MAIL            VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO USERS VALUES ('ahamaide', '2024-01-01', 'HE', 'password', 'mail');
INSERT INTO USERS VALUES ('trichier', '2024-01-01', 'HE', 'password', 'mail2');

CREATE TABLE ALBUM (
    ALBUM_NAME VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(32) NOT NULL,
    PRIMARY KEY (ALBUM_NAME, USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

INSERT INTO ALBUM VALUES ('ahamaide''s album', 'ahamaide');
INSERT INTO ALBUM VALUES ('album4', 'ahamaide');
INSERT INTO ALBUM VALUES ('trichier''s album', 'trichier');