DROP TABLE IF EXISTS MEMORY;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USERNAME        VARCHAR(32) PRIMARY KEY,
    BIRTH_DATE      VARCHAR(10) NOT NULL,
    USER_IDENTITY   VARCHAR(5) NOT NULL,
    PWD             VARCHAR(255) NOT NULL,
    MAIL            VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO USERS VALUES ('ahamaide', '2024-01-01', 'HE', 'password', 'mail');
INSERT INTO USERS VALUES ('trichier', '2024-01-01', 'HE', 'password', 'mail2');

CREATE TABLE ALBUM (
    ALBUM_NAME VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(32) NOT NULL,
    PRIMARY KEY (ALBUM_NAME, USERNAME),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

INSERT INTO ALBUM VALUES ('ahamaide''s album', 'ahamaide');
INSERT INTO ALBUM VALUES ('trichier''s album', 'trichier');

CREATE TABLE MEMORY (
    ALBUM_NAME VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(32) NOT NULL,
    TEXT_CONTENT VARCHAR(255),
    MEDIA_NAME VARCHAR(255),
    MEMORY_DATETIME VARCHAR(19) NOT NULL,
    MOOD VARCHAR(32) NOT NULL,
    PRIMARY KEY (ALBUM_NAME, USERNAME, MEMORY_DATETIME),
    FOREIGN KEY (ALBUM_NAME, USERNAME) REFERENCES ALBUM(ALBUM_NAME, USERNAME) ON DELETE CASCADE
);

INSERT INTO MEMORY
VALUES ('ahamaide''s album', 'ahamaide', 'Je suis patate', 'test_img.png', '2024-01-01 12:12:12', 'happy'),
       ('trichier''s album', 'trichier', 'Je suis tomate', NULL, '2024-01-01 12:12:12', 'sad'),
       ('ahamaide''s album', 'ahamaide', 'Je suis AAAAAH', NULL, '2024-01-01 12:12:13', 'angry');
