DROP TABLE IF EXISTS MEMORY;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USERNAME        VARCHAR(32) PRIMARY KEY,
    BIRTH_DATE      VARCHAR(10) NOT NULL,
    USER_IDENTITY   VARCHAR(5) NOT NULL,
    PWD             VARCHAR(255) NOT NULL,
    MAIL            VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO USERS VALUES ('ahamaide', '2024-01-01', 'HE', 'password', 'mail');
INSERT INTO USERS VALUES ('theo', '2024-01-01', 'HE', 'password', 'mail2');

CREATE TABLE MEMORY (
    USERNAME VARCHAR(32) NOT NULL,
    TEXT_CONTENT VARCHAR(255),
    MEDIA_NAME VARCHAR(255),
    MEMORY_DATETIME VARCHAR(19) NOT NULL,
    PRIMARY KEY (USERNAME, MEMORY_DATETIME),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME) ON DELETE CASCADE
);

INSERT INTO MEMORY
VALUES ('ahamaide', 'Je suis patate', NULL, '2024-01-01:12-12-12'),
       ('theo', 'Je suis tomate', NULL, '2024-01-01:12-12-12'),
       ('ahamaide', 'Je suis AAAAAH', NULL, '2024-01-01:12-12-13');
