DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USERNAME        VARCHAR(32) PRIMARY KEY,
    BIRTH_DATE      VARCHAR(10) NOT NULL,
    USER_IDENTITY   VARCHAR(5) NOT NULL,
    PWD             VARCHAR(255) NOT NULL,
    MAIL            VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO USERS VALUES ('ahamaide', '2024-01-01', 'HE', 'password', 'mail');