DROP TABLE IF EXISTS MEMORY;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USERNAME        VARCHAR(32) PRIMARY KEY,
    BIRTH_DATE      VARCHAR(10) NOT NULL,
    USER_IDENTITY   VARCHAR(5) NOT NULL,
    PWD             VARCHAR(255) NOT NULL,
    MAIL            VARCHAR(255) NOT NULL UNIQUE,
    COLOR_THEME     VARCHAR(32) NOT NULL,
    PROFILE_PICTURE VARCHAR(255)
);

INSERT INTO USERS (USERNAME, BIRTH_DATE, USER_IDENTITY, PWD, MAIL, COLOR_THEME, PROFILE_PICTURE) VALUES ('ahamaide', '2024-01-01', 'HE', 'password', 'mail', 'uranus', 'profilePicture.png');